name: timeago_flutter
description: Timeago Widget for Flutter to create fuzzy timestamps. (e.g. "15 minutes ago").
version: 1.2.0
publish_to: none
homepage: https://github.com/andresaraujo/timeago.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  timeago:
    git:
      url: https://github.com/sumitsharansatsangi/timeago.git
      path: ./packages/timeago
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
