name: timeago
description: >
  A library useful for creating fuzzy timestamps. (e.g. "15 minutes ago")
version: 3.3.0+k1
publish_to: none
homepage: https://github.com/andresaraujo/timeago.dart

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  intl: ^0.18.0

dev_dependencies:
  test: ^1.22.2
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
